export CHEF_PROFILE=default
knife client list
knife node delete node-linux-20
knife node delete node-linux-19
knife node delete node-linux-18
knife node delete node-linux-17
knife node delete node-linux-16
knife node delete node-linux-15
knife node delete node-linux-14
knife node delete node-linux-13
knife node delete node-linux-12
knife node delete node-linux-11
knife node delete node-linux-10
knife node delete node-linux-09
knife node delete node-linux-08
knife node delete node-linux-07
knife node delete node-linux-06
knife node delete node-linux-05
knife node delete node-linux-04
knife node delete node-linux-03
knife client delete node-linux-03
knife client delete node-linux-04
knife client delete node-linux-05
knife client delete node-linux-06
knife client delete node-linux-07
knife client delete node-linux-08
knife client delete node-linux-09
knife client delete node-linux-10
knife client delete node-linux-11
knife client delete node-linux-12
knife client delete node-linux-13
knife client delete node-linux-14
knife client delete node-linux-15
knife client delete node-linux-16
knife client delete node-linux-17
knife client delete node-linux-18
knife client delete node-linux-19
knife client delete node-linux-20