#!/bin/bash
export CHEF_PROFILE=default
knife client list
knife node delete node-linux-20 -y
knife node delete node-linux-19 -y
knife node delete node-linux-18 -y
knife node delete node-linux-17 -y
knife node delete node-linux-16 -y
knife node delete node-linux-15 -y
knife node delete node-linux-14 -y
knife node delete node-linux-13 -y
knife node delete node-linux-12 -y
knife node delete node-linux-11 -y
knife node delete node-linux-10 -y
knife node delete node-linux-09 -y
knife node delete node-linux-08 -y
knife node delete node-linux-07 -y
knife node delete node-linux-06 -y
knife node delete node-linux-05 -y
knife node delete node-linux-04 -y
knife node delete node-linux-03 -y
knife client delete node-linux-03 -y
knife client delete node-linux-04 -y
knife client delete node-linux-05 -y
knife client delete node-linux-06 -y
knife client delete node-linux-07 -y
knife client delete node-linux-08 -y
knife client delete node-linux-09 -y
knife client delete node-linux-10 -y
knife client delete node-linux-11 -y
knife client delete node-linux-12 -y
knife client delete node-linux-13 -y
knife client delete node-linux-14 -y
knife client delete node-linux-15 -y
knife client delete node-linux-16 -y
knife client delete node-linux-17 -y
knife client delete node-linux-18 -y
knife client delete node-linux-19 -y
knife client delete node-linux-20 -y