#!/bin/bash

ssh -i ~/.ssh/sys_admin.pem ubuntu@node-linux-03 "sudo rm /etc/chef/client.rb"
ssh -i ~/.ssh/sys_admin.pem ubuntu@node-linux-04 "sudo rm /etc/chef/client.rb"
ssh -i ~/.ssh/sys_admin.pem ubuntu@node-linux-05 "sudo rm /etc/chef/client.rb"
ssh -i ~/.ssh/sys_admin.pem ubuntu@node-linux-06 "sudo rm /etc/chef/client.rb"
ssh -i ~/.ssh/sys_admin.pem ubuntu@node-linux-07 "sudo rm /etc/chef/client.rb"
ssh -i ~/.ssh/sys_admin.pem ubuntu@node-linux-08 "sudo rm /etc/chef/client.rb"
ssh -i ~/.ssh/sys_admin.pem ubuntu@node-linux-09 "sudo rm /etc/chef/client.rb"
ssh -i ~/.ssh/sys_admin.pem ubuntu@node-linux-10 "sudo rm /etc/chef/client.rb"
ssh -i ~/.ssh/sys_admin.pem ubuntu@node-linux-11 "sudo rm /etc/chef/client.rb"
ssh -i ~/.ssh/sys_admin.pem ubuntu@node-linux-12 "sudo rm /etc/chef/client.rb"
ssh -i ~/.ssh/sys_admin.pem ubuntu@node-linux-13 "sudo rm /etc/chef/client.rb"
ssh -i ~/.ssh/sys_admin.pem ubuntu@node-linux-14 "sudo rm /etc/chef/client.rb"
ssh -i ~/.ssh/sys_admin.pem ubuntu@node-linux-15 "sudo rm /etc/chef/client.rb"
ssh -i ~/.ssh/sys_admin.pem ubuntu@node-linux-16 "sudo rm /etc/chef/client.rb"
ssh -i ~/.ssh/sys_admin.pem ubuntu@node-linux-17 "sudo rm /etc/chef/client.rb"
ssh -i ~/.ssh/sys_admin.pem ubuntu@node-linux-18 "sudo rm /etc/chef/client.rb"
ssh -i ~/.ssh/sys_admin.pem ubuntu@node-linux-19 "sudo rm /etc/chef/client.rb"
ssh -i ~/.ssh/sys_admin.pem ubuntu@node-linux-20 "sudo rm /etc/chef/client.rb"