name 'base'
maintainer 'Mike Butler'
maintainer_email 'michael.butler@progress.com'
license 'All Rights Reserved'
description 'Installs/Configures base'
version '0.2.0'
chef_version '>= 18.0'

# depends 'benchmarks'
# depends 'remediation_stig_winstig2019_v2_2_0_wrapper'
# depends 'remediation_stig_ubuntu2004_v1_2_0_wrapper'